import type { Guest } from '@podcast-crm/types';

export const WORKSPACE_ID = 'ws_demo_01';

export const seedGuests: Guest[] = [
  // --- DISCOVER (6 guests) ---
  {
    id: 'guest_001',
    workspaceId: WORKSPACE_ID,
    name: 'James Okafor',
    email: 'james.okafor@sequoiacap.com',
    title: 'General Partner',
    company: 'Sequoia Capital',
    bio: 'James Okafor is a General Partner at Sequoia Capital with 15 years of experience backing transformative technology companies. He led investments in three unicorns in the AI infrastructure space and is a sought-after voice on the future of venture capital and startup ecosystems.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=JamesOkafor',
    linkedinUrl: 'https://linkedin.com/in/jamesokafor',
    twitterHandle: 'jokafor_vc',
    websiteUrl: 'https://sequoiacap.com',
    topics: ['venture capital', 'AI infrastructure', 'startup ecosystems', 'fundraising'],
    fitScore: 91,
    stage: 'discover',
    priority: 'high',
    notes:
      'Found via LinkedIn mutual connection with Andreessen. Posted a thread on AI moats last week that got 50k impressions.',
    outreachCount: 0,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'guest_002',
    workspaceId: WORKSPACE_ID,
    name: 'Dr. Amara Osei',
    email: 'amara.osei@mit.edu',
    title: 'Associate Professor of Computational Biology',
    company: 'MIT',
    bio: 'Dr. Amara Osei leads the Computational Genomics Lab at MIT, where her team applies machine learning to accelerate drug discovery. Her paper on protein folding optimization was cited over 3,000 times in 2025.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=AmaraOsei',
    linkedinUrl: 'https://linkedin.com/in/dramaraosei',
    twitterHandle: 'amara_bio',
    websiteUrl: 'https://compgen.mit.edu',
    topics: ['computational biology', 'drug discovery', 'machine learning', 'genomics'],
    fitScore: 87,
    stage: 'discover',
    priority: 'high',
    notes: 'Referred by Dr. Sarah Chen. Published landmark paper in Nature in January 2026.',
    outreachCount: 0,
    createdAt: '2026-02-03T09:00:00Z',
    updatedAt: '2026-02-03T09:00:00Z',
  },
  {
    id: 'guest_003',
    workspaceId: WORKSPACE_ID,
    name: 'Tyler Nguyen',
    email: 'tyler@replicate.com',
    title: 'Co-Founder & CEO',
    company: 'Replicate',
    bio: 'Tyler Nguyen co-founded Replicate, the platform that democratized access to open-source AI models. Under his leadership, Replicate grew to serve over 500,000 developers and was valued at $1B in their Series C.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=TylerNguyen',
    linkedinUrl: 'https://linkedin.com/in/tylernguyen',
    twitterHandle: 'tylernguyen',
    websiteUrl: 'https://replicate.com',
    topics: ['open source AI', 'developer tools', 'MLOps', 'startup scaling'],
    fitScore: 89,
    stage: 'discover',
    priority: 'high',
    notes:
      'Spoke at NeurIPS 2025. Very active on Twitter. Would be great for our "AI Infrastructure" episode series.',
    outreachCount: 0,
    createdAt: '2026-02-05T14:00:00Z',
    updatedAt: '2026-02-05T14:00:00Z',
  },
  {
    id: 'guest_004',
    workspaceId: WORKSPACE_ID,
    name: 'Fatima Al-Rashid',
    email: 'fatima@moonshot.vc',
    title: 'Principal',
    company: 'Moonshot Ventures',
    bio: 'Fatima Al-Rashid is a Principal at Moonshot Ventures focusing on climate tech and sustainable AI. She was named Forbes 30 Under 30 in 2024 and writes a popular newsletter on impact investing with 80,000 subscribers.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=FatimaAlRashid',
    linkedinUrl: 'https://linkedin.com/in/fatimaalrashid',
    twitterHandle: 'fatima_vc',
    websiteUrl: 'https://moonshot.vc',
    topics: ['climate tech', 'impact investing', 'sustainable AI', 'diversity in VC'],
    fitScore: 82,
    stage: 'discover',
    priority: 'medium',
    notes: 'Newsletter subscriber. Engaged with our last 3 LinkedIn posts.',
    outreachCount: 0,
    createdAt: '2026-02-07T11:00:00Z',
    updatedAt: '2026-02-07T11:00:00Z',
  },
  {
    id: 'guest_005',
    workspaceId: WORKSPACE_ID,
    name: 'Ben Horowitz',
    email: 'ben@a16z.com',
    title: 'Co-Founder & General Partner',
    company: 'Andreessen Horowitz',
    bio: "Ben Horowitz is the co-founder and General Partner at Andreessen Horowitz (a16z), one of Silicon Valley's most prominent venture capital firms. He is the author of 'The Hard Thing About Hard Things' and 'What You Do Is Who You Are'.",
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=BenHorowitz',
    linkedinUrl: 'https://linkedin.com/in/bhorowitz',
    twitterHandle: 'bhorowitz',
    websiteUrl: 'https://a16z.com',
    topics: ['venture capital', 'leadership', 'company culture', 'technology trends'],
    fitScore: 95,
    stage: 'discover',
    priority: 'high',
    notes:
      'Dream guest. Long shot but worth trying via warm intro from Tyler Nguyen if that relationship develops.',
    outreachCount: 0,
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-02-10T08:00:00Z',
  },
  {
    id: 'guest_006',
    workspaceId: WORKSPACE_ID,
    name: 'Zara Mensah',
    email: 'zara@humanloop.com',
    title: 'Head of Product',
    company: 'Humanloop',
    bio: 'Zara Mensah leads product at Humanloop, the platform for building and evaluating LLM applications. She was previously a PM at Notion and DeepMind. Known for her sharp thinking on AI product development and the emerging field of LLM evaluation.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=ZaraMensah',
    linkedinUrl: 'https://linkedin.com/in/zaramensah',
    twitterHandle: 'zara_pm',
    websiteUrl: 'https://humanloop.com',
    topics: ['AI products', 'LLM evaluation', 'product management', 'developer experience'],
    fitScore: 85,
    stage: 'discover',
    priority: 'medium',
    notes: 'Appeared on Lenny Podcast in Jan 2026. Great communicator.',
    outreachCount: 0,
    createdAt: '2026-02-12T13:00:00Z',
    updatedAt: '2026-02-12T13:00:00Z',
  },

  // --- OUTREACH (6 guests) ---
  {
    id: 'guest_007',
    workspaceId: WORKSPACE_ID,
    name: 'Dr. Sarah Chen',
    email: 'sarah.chen@deepmind.com',
    title: 'AI Research Lead',
    company: 'Google DeepMind',
    bio: 'Dr. Sarah Chen is an AI Research Lead at Google DeepMind, specializing in AI safety and alignment. She holds a PhD from Stanford and has published 40+ papers on machine learning safety. Her work on constitutional AI has been pivotal in shaping industry standards.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=SarahChen',
    linkedinUrl: 'https://linkedin.com/in/drsarahchen',
    twitterHandle: 'sarah_ai_safety',
    websiteUrl: 'https://deepmind.google',
    topics: ['AI safety', 'machine learning', 'alignment', 'responsible AI'],
    fitScore: 96,
    stage: 'outreach',
    priority: 'high',
    notes:
      'First email sent Feb 15. Opened but no reply. Sent follow-up Feb 22. Waiting on response.',
    outreachCount: 2,
    lastContactedAt: '2026-02-22T10:00:00Z',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-02-22T10:00:00Z',
  },
  {
    id: 'guest_008',
    workspaceId: WORKSPACE_ID,
    name: 'David Kim',
    email: 'david.kim@stripe.com',
    title: 'VP of Engineering',
    company: 'Stripe',
    bio: 'David Kim is the VP of Engineering at Stripe, overseeing the infrastructure powering global payments. He joined Stripe as their 12th engineer and has scaled teams from 10 to 400+ engineers. He writes about engineering leadership and distributed systems.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=DavidKim',
    linkedinUrl: 'https://linkedin.com/in/davidkimstripe',
    twitterHandle: 'davidkim_eng',
    websiteUrl: 'https://stripe.com',
    topics: ['engineering leadership', 'distributed systems', 'fintech', 'team scaling'],
    fitScore: 90,
    stage: 'outreach',
    priority: 'high',
    notes: 'Initial email sent. He replied with "sounds interesting, send more details." Follow-up pending.',
    outreachCount: 1,
    lastContactedAt: '2026-02-18T14:30:00Z',
    createdAt: '2026-01-25T09:00:00Z',
    updatedAt: '2026-02-18T14:30:00Z',
  },
  {
    id: 'guest_009',
    workspaceId: WORKSPACE_ID,
    name: 'Lena Fischer',
    email: 'lena.fischer@mistral.ai',
    title: 'Research Scientist',
    company: 'Mistral AI',
    bio: 'Lena Fischer is a Research Scientist at Mistral AI, contributing to the development of open-weight language models that rival proprietary systems. Previously at Meta AI. She is a vocal advocate for open-source AI and European tech sovereignty.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=LenaFischer',
    linkedinUrl: 'https://linkedin.com/in/lenafischer',
    twitterHandle: 'lena_mistral',
    websiteUrl: 'https://mistral.ai',
    topics: ['open source AI', 'language models', 'European tech', 'AI policy'],
    fitScore: 88,
    stage: 'outreach',
    priority: 'medium',
    notes: 'DM sent via Twitter. She liked the message but no follow-up reply yet.',
    outreachCount: 1,
    lastContactedAt: '2026-02-20T11:00:00Z',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-20T11:00:00Z',
  },
  {
    id: 'guest_010',
    workspaceId: WORKSPACE_ID,
    name: 'Carlos Mendez',
    email: 'carlos@growthplaybook.io',
    title: 'Founder & Growth Strategist',
    company: 'Growth Playbook',
    bio: 'Carlos Mendez is the founder of Growth Playbook, a consultancy that has helped 200+ SaaS companies achieve breakout growth. He scaled three startups from $0 to $10M ARR and documented every playbook publicly. His course on B2B growth has 25,000 students.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=CarlosMendez',
    linkedinUrl: 'https://linkedin.com/in/carlosmendez',
    twitterHandle: 'carlosgrowth',
    websiteUrl: 'https://growthplaybook.io',
    topics: ['growth hacking', 'SaaS', 'B2B marketing', 'product-led growth'],
    fitScore: 83,
    stage: 'outreach',
    priority: 'medium',
    notes: 'Responded positively. Waiting for him to confirm availability.',
    outreachCount: 2,
    lastContactedAt: '2026-02-25T09:00:00Z',
    createdAt: '2026-02-05T12:00:00Z',
    updatedAt: '2026-02-25T09:00:00Z',
  },
  {
    id: 'guest_011',
    workspaceId: WORKSPACE_ID,
    name: 'Nia Johnson',
    email: 'nia@notboring.co',
    title: 'Author & Technology Analyst',
    company: 'Not Boring',
    bio: 'Nia Johnson is an author and technology analyst at Not Boring, one of the most widely-read newsletters on business strategy and technology. Her long-form essays on emerging tech have attracted 400,000 subscribers and shaped conversations at the highest levels of tech.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=NiaJohnson',
    linkedinUrl: 'https://linkedin.com/in/niajohnson',
    twitterHandle: 'niajohnson',
    websiteUrl: 'https://notboring.co',
    topics: ['technology strategy', 'media', 'future of work', 'creator economy'],
    fitScore: 86,
    stage: 'outreach',
    priority: 'high',
    notes: 'First email bounced. Found alternate email. Resending.',
    outreachCount: 1,
    lastContactedAt: '2026-02-28T10:00:00Z',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-28T10:00:00Z',
  },
  {
    id: 'guest_012',
    workspaceId: WORKSPACE_ID,
    name: 'Alex Rivera',
    email: 'alex@remotefirst.io',
    title: 'Co-Founder & CEO',
    company: 'RemoteFirst',
    bio: 'Alex Rivera co-founded RemoteFirst, a platform that helps companies build and manage distributed engineering teams. He grew the company to $5M ARR in 18 months with a fully remote team of 40 across 12 countries.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=AlexRivera',
    linkedinUrl: 'https://linkedin.com/in/alexrivera',
    twitterHandle: 'alexremote',
    websiteUrl: 'https://remotefirst.io',
    topics: ['remote work', 'distributed teams', 'startup operations', 'hiring'],
    fitScore: 79,
    stage: 'outreach',
    priority: 'low',
    notes: 'Third attempt. If no reply by March 15, move to archive.',
    outreachCount: 3,
    lastContactedAt: '2026-03-01T09:00:00Z',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-01T09:00:00Z',
  },

  // --- SCHEDULED (5 guests) ---
  {
    id: 'guest_013',
    workspaceId: WORKSPACE_ID,
    name: 'Marcus Rivera',
    email: 'marcus@growthlabs.io',
    title: 'Founder & CEO',
    company: 'GrowthLabs',
    bio: 'Marcus Rivera is the founder of GrowthLabs, a performance marketing agency that generated $2B in revenue for D2C brands. He pioneered the "full-funnel AI" approach to paid acquisition and shares his strategies openly on LinkedIn and his weekly podcast.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=MarcusRivera',
    linkedinUrl: 'https://linkedin.com/in/marcusrivera',
    twitterHandle: 'marcus_growth',
    websiteUrl: 'https://growthlabs.io',
    topics: ['performance marketing', 'D2C brands', 'paid acquisition', 'growth strategy'],
    fitScore: 88,
    stage: 'scheduled',
    priority: 'high',
    notes: 'Confirmed for March 20th at 2pm ET. Cal invite sent. Prep brief needed.',
    episodeTitle: 'The Full-Funnel AI Playbook',
    recordingDate: '2026-03-20T18:00:00Z',
    outreachCount: 2,
    lastContactedAt: '2026-03-01T14:00:00Z',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-03-01T14:00:00Z',
  },
  {
    id: 'guest_014',
    workspaceId: WORKSPACE_ID,
    name: 'Dr. Kwame Asante',
    email: 'kwame.asante@stanford.edu',
    title: 'Professor of Human-Computer Interaction',
    company: 'Stanford University',
    bio: 'Dr. Kwame Asante is a Professor of HCI at Stanford, where he runs the Future of Human-AI Collaboration lab. His research focuses on how AI systems should communicate uncertainty to humans. TED talk from 2025 has 8 million views.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=KwameAsante',
    linkedinUrl: 'https://linkedin.com/in/drkwameasante',
    twitterHandle: 'kwame_hci',
    websiteUrl: 'https://hci.stanford.edu',
    topics: ['human-computer interaction', 'AI communication', 'UX research', 'future of AI'],
    fitScore: 92,
    stage: 'scheduled',
    priority: 'high',
    notes: 'Recording March 25 at 11am PT. Guest very enthusiastic. Pre-brief sent.',
    episodeTitle: 'When AI Gets Uncertain: Designing for Trust',
    recordingDate: '2026-03-25T15:00:00Z',
    outreachCount: 1,
    lastContactedAt: '2026-02-28T10:00:00Z',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-28T10:00:00Z',
  },
  {
    id: 'guest_015',
    workspaceId: WORKSPACE_ID,
    name: 'Aisha Patel',
    email: 'aisha@modal.com',
    title: 'CTO & Co-Founder',
    company: 'Modal Labs',
    bio: "Aisha Patel is the CTO and co-founder of Modal Labs, which lets developers run cloud functions on GPUs with 3-line Python. She previously built infrastructure at Jump Trading and holds patents in distributed computing. Modal's developer-first approach has attracted 30,000 engineers.",
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=AishaPatel',
    linkedinUrl: 'https://linkedin.com/in/aishapatel',
    twitterHandle: 'aisha_modal',
    websiteUrl: 'https://modal.com',
    topics: ['cloud infrastructure', 'GPU computing', 'developer tools', 'MLOps'],
    fitScore: 94,
    stage: 'scheduled',
    priority: 'high',
    notes: 'April 2 at 10am ET. Sending technical questions in advance.',
    episodeTitle: 'GPUs for Everyone: The Infrastructure Revolution',
    recordingDate: '2026-04-02T14:00:00Z',
    outreachCount: 1,
    lastContactedAt: '2026-03-05T09:00:00Z',
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-03-05T09:00:00Z',
  },
  {
    id: 'guest_016',
    workspaceId: WORKSPACE_ID,
    name: 'Jordan West',
    email: 'jordan@brandpilot.ai',
    title: 'Founder',
    company: 'BrandPilot AI',
    bio: 'Jordan West is the founder of BrandPilot AI, an AI-native brand strategy platform for mid-market companies. He bootstrapped the company to $2.5M ARR and built a YouTube channel documenting the entire journey with 180,000 subscribers.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=JordanWest',
    linkedinUrl: 'https://linkedin.com/in/jordanwest',
    twitterHandle: 'jordanwest_ai',
    websiteUrl: 'https://brandpilot.ai',
    topics: ['AI for business', 'bootstrapping', 'brand strategy', 'content marketing'],
    fitScore: 81,
    stage: 'scheduled',
    priority: 'medium',
    notes: 'March 28 at 3pm ET. Very excited. Has a great story angle.',
    episodeTitle: 'Bootstrapping to $2.5M: The AI Brand Revolution',
    recordingDate: '2026-03-28T19:00:00Z',
    outreachCount: 2,
    lastContactedAt: '2026-03-06T11:00:00Z',
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-03-06T11:00:00Z',
  },
  {
    id: 'guest_017',
    workspaceId: WORKSPACE_ID,
    name: 'Dr. Priya Kapoor',
    email: 'priya.kapoor@openai.com',
    title: 'Research Scientist, Safety Team',
    company: 'OpenAI',
    bio: 'Dr. Priya Kapoor is a Research Scientist on OpenAI\'s safety team. She leads research on interpretability and mechanistic understanding of large language models. Her work on "superposition" in neural networks has become a foundational paper in the field.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=PriyaKapoor',
    linkedinUrl: 'https://linkedin.com/in/drpriyakapoor',
    twitterHandle: 'priya_safety',
    websiteUrl: 'https://openai.com',
    topics: ['AI interpretability', 'mechanistic AI', 'neural network safety', 'AI research'],
    fitScore: 93,
    stage: 'scheduled',
    priority: 'high',
    notes:
      'April 5 at 2pm PT. Cleared by OpenAI comms. Very rare access — treat with extra care.',
    episodeTitle: 'Inside the Black Box: Understanding AI from the Inside Out',
    recordingDate: '2026-04-05T21:00:00Z',
    outreachCount: 3,
    lastContactedAt: '2026-03-07T15:00:00Z',
    createdAt: '2026-01-05T10:00:00Z',
    updatedAt: '2026-03-07T15:00:00Z',
  },

  // --- RECORDED (4 guests) ---
  {
    id: 'guest_018',
    workspaceId: WORKSPACE_ID,
    name: 'Sophie Laurent',
    email: 'sophie@huggingface.co',
    title: 'Head of Developer Relations',
    company: 'Hugging Face',
    bio: 'Sophie Laurent is Head of Developer Relations at Hugging Face, the GitHub of machine learning. She helped grow the community from 10,000 to 500,000 model uploads and is a passionate advocate for open-source AI. Born in Lyon, based in New York.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=SophieLaurent',
    linkedinUrl: 'https://linkedin.com/in/sophielaurent',
    twitterHandle: 'sophie_hf',
    websiteUrl: 'https://huggingface.co',
    topics: ['open source AI', 'developer communities', 'MLOps', 'model hubs'],
    fitScore: 90,
    stage: 'recorded',
    priority: 'high',
    notes: 'Recorded Feb 28. Fantastic energy. Episode in editing queue.',
    episodeTitle: "The Open Source AI Revolution — Hugging Face's Community Story",
    episodeNumber: 48,
    recordingDate: '2026-02-28T15:00:00Z',
    outreachCount: 1,
    lastContactedAt: '2026-02-28T15:00:00Z',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-02-28T15:00:00Z',
  },
  {
    id: 'guest_019',
    workspaceId: WORKSPACE_ID,
    name: 'Raj Mehta',
    email: 'raj@dbtlabs.com',
    title: 'VP of Product',
    company: 'dbt Labs',
    bio: 'Raj Mehta is VP of Product at dbt Labs, building the data transformation layer used by 30,000 companies. He previously led product at Looker and has spent his career at the intersection of data engineering and business intelligence.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=RajMehta',
    linkedinUrl: 'https://linkedin.com/in/rajmehta',
    twitterHandle: 'raj_dbt',
    websiteUrl: 'https://getdbt.com',
    topics: ['data engineering', 'analytics engineering', 'data transformation', 'modern data stack'],
    fitScore: 85,
    stage: 'recorded',
    priority: 'medium',
    notes: 'Recorded March 3. Strong episode on the modern data stack.',
    episodeTitle: 'The Analytics Engineering Revolution',
    episodeNumber: 49,
    recordingDate: '2026-03-03T14:00:00Z',
    outreachCount: 2,
    lastContactedAt: '2026-03-03T14:00:00Z',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-03-03T14:00:00Z',
  },
  {
    id: 'guest_020',
    workspaceId: WORKSPACE_ID,
    name: 'Isabelle Dupont',
    email: 'isabelle@cohere.com',
    title: 'Head of Enterprise AI',
    company: 'Cohere',
    bio: 'Isabelle Dupont leads enterprise AI adoption at Cohere, helping Fortune 500 companies integrate large language models into core business processes. She spent 8 years at McKinsey before joining the AI industry and brings a rare perspective on enterprise transformation.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=IsabelleDupont',
    linkedinUrl: 'https://linkedin.com/in/isabelledupont',
    twitterHandle: 'isabelle_ai',
    websiteUrl: 'https://cohere.com',
    topics: ['enterprise AI', 'LLM deployment', 'business transformation', 'AI strategy'],
    fitScore: 87,
    stage: 'recorded',
    priority: 'high',
    notes: 'Recorded March 5. Great enterprise perspective. Post-production in progress.',
    episodeTitle: 'Enterprise AI: The Real Story Beyond the Hype',
    episodeNumber: 50,
    recordingDate: '2026-03-05T16:00:00Z',
    outreachCount: 1,
    lastContactedAt: '2026-03-05T16:00:00Z',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-03-05T16:00:00Z',
  },
  {
    id: 'guest_021',
    workspaceId: WORKSPACE_ID,
    name: 'Nathan Brooks',
    email: 'nathan@convex.dev',
    title: 'Founder & CEO',
    company: 'Convex',
    bio: 'Nathan Brooks is the founder and CEO of Convex, the reactive database for modern web apps. He was previously a core engineer at Dropbox, working on sync infrastructure for 700 million users. Convex has become a darling in the developer tools space.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=NathanBrooks',
    linkedinUrl: 'https://linkedin.com/in/nathanbrooks',
    twitterHandle: 'nathanconvex',
    websiteUrl: 'https://convex.dev',
    topics: ['developer tools', 'databases', 'reactive systems', 'full-stack development'],
    fitScore: 88,
    stage: 'recorded',
    priority: 'medium',
    notes: 'Recorded March 7. Very technical episode — great for developer audience.',
    episodeTitle: 'Reactive Databases and the Future of Full-Stack Dev',
    episodeNumber: 51,
    recordingDate: '2026-03-07T15:00:00Z',
    outreachCount: 2,
    lastContactedAt: '2026-03-07T15:00:00Z',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-03-07T15:00:00Z',
  },

  // --- PUBLISHED (8 guests) ---
  {
    id: 'guest_022',
    workspaceId: WORKSPACE_ID,
    name: 'Priya Sharma',
    email: 'priya@priyasharma.com',
    title: 'Author & Speaker',
    company: 'Independent',
    bio: "Priya Sharma is a bestselling author and international speaker on the future of work and AI. Her book 'Work Reimagined' sold 300,000 copies and was translated into 18 languages. She advises Fortune 100 companies on AI workforce strategy.",
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=PriyaSharma',
    linkedinUrl: 'https://linkedin.com/in/priyasharma',
    twitterHandle: 'priyasharma',
    websiteUrl: 'https://priyasharma.com',
    topics: ['future of work', 'AI and jobs', 'workforce transformation', 'leadership'],
    fitScore: 91,
    stage: 'published',
    priority: 'high',
    notes: 'Ep 42 was our highest-rated episode. 45k downloads. Consider for a return episode.',
    episodeTitle: 'Work Reimagined: AI, Humans, and the Jobs of 2030',
    episodeNumber: 42,
    recordingDate: '2025-11-15T15:00:00Z',
    publishedDate: '2025-12-01T09:00:00Z',
    podcastUrl: 'https://podcast.example.com/episodes/42',
    outreachCount: 1,
    lastContactedAt: '2025-11-15T15:00:00Z',
    createdAt: '2025-10-01T10:00:00Z',
    updatedAt: '2025-12-01T09:00:00Z',
  },
  {
    id: 'guest_023',
    workspaceId: WORKSPACE_ID,
    name: 'Tom Preston-Werner',
    email: 'tom@tom.com',
    title: 'Founder',
    company: 'GitHub (former), Preston-Werner Ventures',
    bio: 'Tom Preston-Werner co-founded GitHub and grew it to 28 million developers before its acquisition by Microsoft for $7.5B. He now runs Preston-Werner Ventures and builds open-source tools. His perspective on developer communities is unmatched.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=TomPrestonWerner',
    linkedinUrl: 'https://linkedin.com/in/mojombo',
    twitterHandle: 'mojombo',
    websiteUrl: 'https://tom.com',
    topics: ['open source', 'developer communities', 'startups', 'exits'],
    fitScore: 97,
    stage: 'published',
    priority: 'high',
    notes: 'Ep 43. Legendary episode. Massive spike in subscribers.',
    episodeTitle: "GitHub to $7.5B: Tom Preston-Werner's Unfiltered Story",
    episodeNumber: 43,
    recordingDate: '2025-12-01T15:00:00Z',
    publishedDate: '2025-12-15T09:00:00Z',
    podcastUrl: 'https://podcast.example.com/episodes/43',
    outreachCount: 2,
    lastContactedAt: '2025-12-01T15:00:00Z',
    createdAt: '2025-10-10T10:00:00Z',
    updatedAt: '2025-12-15T09:00:00Z',
  },
  {
    id: 'guest_024',
    workspaceId: WORKSPACE_ID,
    name: 'Kelsey Hightower',
    email: 'kelsey@google.com',
    title: 'Principal Engineer',
    company: 'Google',
    bio: "Kelsey Hightower is a Principal Engineer at Google and one of the most respected voices in cloud-native computing. He is co-author of 'Kubernetes: Up and Running' and a legendary conference speaker known for his live demos.",
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=KelseyHightower',
    linkedinUrl: 'https://linkedin.com/in/kelseyhightower',
    twitterHandle: 'kelseyhightower',
    websiteUrl: 'https://google.com',
    topics: ['Kubernetes', 'cloud native', 'DevOps', 'platform engineering'],
    fitScore: 93,
    stage: 'published',
    priority: 'high',
    notes: 'Ep 44. Developer audience went wild. 60k downloads — record.',
    episodeTitle: "Kubernetes: The Real Story from the Person Who Made It Famous",
    episodeNumber: 44,
    recordingDate: '2026-01-05T16:00:00Z',
    publishedDate: '2026-01-15T09:00:00Z',
    podcastUrl: 'https://podcast.example.com/episodes/44',
    outreachCount: 1,
    lastContactedAt: '2026-01-05T16:00:00Z',
    createdAt: '2025-11-01T10:00:00Z',
    updatedAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'guest_025',
    workspaceId: WORKSPACE_ID,
    name: 'Shreya Agarwal',
    email: 'shreya@coreweave.com',
    title: 'Director of Strategic Partnerships',
    company: 'CoreWeave',
    bio: 'Shreya Agarwal is Director of Strategic Partnerships at CoreWeave, the GPU cloud that powers some of the world\'s largest AI workloads. She closed $500M in enterprise partnerships in 2025 and is an expert on the GPU supply chain crisis.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=ShreyaAgarwal',
    linkedinUrl: 'https://linkedin.com/in/shreyaagarwal',
    twitterHandle: 'shreya_gpu',
    websiteUrl: 'https://coreweave.com',
    topics: ['GPU infrastructure', 'AI compute', 'cloud partnerships', 'AI supply chain'],
    fitScore: 86,
    stage: 'published',
    priority: 'medium',
    notes: 'Ep 45. Very timely content on compute scarcity.',
    episodeTitle: 'The GPU Gold Rush: Inside the AI Compute Supply Chain',
    episodeNumber: 45,
    recordingDate: '2026-01-15T15:00:00Z',
    publishedDate: '2026-01-22T09:00:00Z',
    podcastUrl: 'https://podcast.example.com/episodes/45',
    outreachCount: 2,
    lastContactedAt: '2026-01-15T15:00:00Z',
    createdAt: '2025-11-15T10:00:00Z',
    updatedAt: '2026-01-22T09:00:00Z',
  },
  {
    id: 'guest_026',
    workspaceId: WORKSPACE_ID,
    name: 'Diego Hernandez',
    email: 'diego@langchain.ai',
    title: 'Co-Founder',
    company: 'LangChain',
    bio: 'Diego Hernandez is a co-founder of LangChain, the framework that became the default building block for LLM applications worldwide. Within 18 months, LangChain surpassed 80,000 GitHub stars and powered applications at thousands of companies.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=DiegoHernandez',
    linkedinUrl: 'https://linkedin.com/in/diegohernandez',
    twitterHandle: 'diego_langchain',
    websiteUrl: 'https://langchain.ai',
    topics: ['LLM applications', 'AI frameworks', 'open source', 'developer tooling'],
    fitScore: 92,
    stage: 'published',
    priority: 'high',
    notes: 'Ep 46. Huge reach. Newsletter grew by 3,000 subs after episode.',
    episodeTitle: "80,000 Stars: How LangChain Became the Foundation of the AI Stack",
    episodeNumber: 46,
    recordingDate: '2026-01-28T15:00:00Z',
    publishedDate: '2026-02-05T09:00:00Z',
    podcastUrl: 'https://podcast.example.com/episodes/46',
    outreachCount: 1,
    lastContactedAt: '2026-01-28T15:00:00Z',
    createdAt: '2025-12-01T10:00:00Z',
    updatedAt: '2026-02-05T09:00:00Z',
  },
  {
    id: 'guest_027',
    workspaceId: WORKSPACE_ID,
    name: 'Monica Singh',
    email: 'monica@elevenlabs.io',
    title: 'Head of Growth',
    company: 'ElevenLabs',
    bio: "Monica Singh is Head of Growth at ElevenLabs, the AI voice platform that's transforming audio content creation. She drove ElevenLabs from 50,000 to 2 million users in under a year using community-led growth strategies.",
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=MonicaSingh',
    linkedinUrl: 'https://linkedin.com/in/monicasingh',
    twitterHandle: 'monica_voice',
    websiteUrl: 'https://elevenlabs.io',
    topics: ['AI voice', 'product-led growth', 'audio AI', 'creator tools'],
    fitScore: 84,
    stage: 'published',
    priority: 'medium',
    notes: 'Ep 47. Very popular with creator audience.',
    episodeTitle: 'Voice Cloning and the Future of Audio AI',
    episodeNumber: 47,
    recordingDate: '2026-02-10T15:00:00Z',
    publishedDate: '2026-02-17T09:00:00Z',
    podcastUrl: 'https://podcast.example.com/episodes/47',
    outreachCount: 1,
    lastContactedAt: '2026-02-10T15:00:00Z',
    createdAt: '2025-12-15T10:00:00Z',
    updatedAt: '2026-02-17T09:00:00Z',
  },
  {
    id: 'guest_028',
    workspaceId: WORKSPACE_ID,
    name: 'Oliver Zhang',
    email: 'oliver@figma.com',
    title: 'Staff Product Designer',
    company: 'Figma',
    bio: 'Oliver Zhang is a Staff Product Designer at Figma who led the design of Figma\'s AI features including the groundbreaking "Make Designs" feature. He has a cult following in the design community for his methodical approach to designing AI interfaces.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=OliverZhang',
    linkedinUrl: 'https://linkedin.com/in/oliverzhang',
    twitterHandle: 'oliver_ux',
    websiteUrl: 'https://figma.com',
    topics: ['AI UX design', 'product design', 'design systems', 'Figma'],
    fitScore: 83,
    stage: 'published',
    priority: 'medium',
    notes: 'Ep 40. Design-focused audience loved it.',
    episodeTitle: "Designing for AI: Figma's Approach to Human-AI Interfaces",
    episodeNumber: 40,
    recordingDate: '2025-11-01T15:00:00Z',
    publishedDate: '2025-11-10T09:00:00Z',
    podcastUrl: 'https://podcast.example.com/episodes/40',
    outreachCount: 2,
    lastContactedAt: '2025-11-01T15:00:00Z',
    createdAt: '2025-09-15T10:00:00Z',
    updatedAt: '2025-11-10T09:00:00Z',
  },
  {
    id: 'guest_029',
    workspaceId: WORKSPACE_ID,
    name: 'Emma Thompson',
    email: 'emma@podcastpros.com',
    title: 'Podcast Host & Media Entrepreneur',
    company: 'Podcast Pros Network',
    bio: 'Emma Thompson is the founder of Podcast Pros Network, a media company that produces 12 top-ranked business podcasts with 5 million monthly listeners. She sold her first podcast production company in 2022 and is now building the next generation of AI-powered podcast infrastructure.',
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=EmmaThompson',
    linkedinUrl: 'https://linkedin.com/in/emmathompson',
    twitterHandle: 'emmapodcast',
    websiteUrl: 'https://podcastpros.com',
    topics: ['podcasting', 'media business', 'audio content', 'entrepreneurship'],
    fitScore: 89,
    stage: 'published',
    priority: 'high',
    notes: 'Ep 41. Perfect guest for our audience. 35k downloads.',
    episodeTitle: 'Building a Podcast Empire: Inside Podcast Pros Network',
    episodeNumber: 41,
    recordingDate: '2025-11-08T15:00:00Z',
    publishedDate: '2025-11-20T09:00:00Z',
    podcastUrl: 'https://podcast.example.com/episodes/41',
    outreachCount: 1,
    lastContactedAt: '2025-11-08T15:00:00Z',
    createdAt: '2025-09-01T10:00:00Z',
    updatedAt: '2025-11-20T09:00:00Z',
  },

  // --- FOLLOW-UP (5 guests) ---
  {
    id: 'guest_030',
    workspaceId: WORKSPACE_ID,
    name: 'Sam Altman',
    email: 'sam@openai.com',
    title: 'CEO',
    company: 'OpenAI',
    bio: "Sam Altman is the CEO of OpenAI, the company behind ChatGPT, DALL-E, and GPT-4. He previously ran Y Combinator and has invested in hundreds of startups. His vision for AGI and its impact on society has made him one of the most discussed figures in technology.",
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=SamAltman',
    linkedinUrl: 'https://linkedin.com/in/samaltman',
    twitterHandle: 'sama',
    websiteUrl: 'https://openai.com',
    topics: ['AGI', 'AI policy', 'OpenAI', 'startup ecosystems'],
    fitScore: 99,
    stage: 'follow_up',
    priority: 'high',
    notes:
      'Published Ep 35. Most downloaded episode ever. 180k downloads. Must get him back for AGI follow-up.',
    episodeTitle: 'Sam Altman on AGI, ChatGPT, and OpenAI\'s Mission',
    episodeNumber: 35,
    recordingDate: '2025-08-15T15:00:00Z',
    publishedDate: '2025-09-01T09:00:00Z',
    podcastUrl: 'https://podcast.example.com/episodes/35',
    nextFollowUpDate: '2026-04-01T09:00:00Z',
    outreachCount: 4,
    lastContactedAt: '2025-09-15T10:00:00Z',
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2025-09-15T10:00:00Z',
  },
  {
    id: 'guest_031',
    workspaceId: WORKSPACE_ID,
    name: 'Andrej Karpathy',
    email: 'andrej@karpathy.ai',
    title: 'Independent Researcher & Educator',
    company: 'Independent (former Tesla, OpenAI)',
    bio: "Andrej Karpathy is one of the most respected AI educators and researchers in the world. He pioneered the application of deep learning at Tesla Autopilot and led AI research at OpenAI. His YouTube lectures on neural networks have 4 million views.",
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=AndrejKarpathy',
    linkedinUrl: 'https://linkedin.com/in/andrejkarpathy',
    twitterHandle: 'karpathy',
    websiteUrl: 'https://karpathy.ai',
    topics: ['deep learning', 'AI education', 'computer vision', 'autonomous vehicles'],
    fitScore: 98,
    stage: 'follow_up',
    priority: 'high',
    notes:
      'Published Ep 37. Engineering community went wild. Follow-up pitch: deep dive on LLM internals.',
    episodeTitle: "Teaching Neural Networks to Millions: Andrej Karpathy's Method",
    episodeNumber: 37,
    recordingDate: '2025-09-10T15:00:00Z',
    publishedDate: '2025-09-20T09:00:00Z',
    podcastUrl: 'https://podcast.example.com/episodes/37',
    nextFollowUpDate: '2026-03-15T09:00:00Z',
    outreachCount: 3,
    lastContactedAt: '2025-10-01T10:00:00Z',
    createdAt: '2025-07-01T10:00:00Z',
    updatedAt: '2025-10-01T10:00:00Z',
  },
  {
    id: 'guest_032',
    workspaceId: WORKSPACE_ID,
    name: 'Gergely Orosz',
    email: 'gergely@pragmaticengineer.com',
    title: 'Author & Newsletter Writer',
    company: 'The Pragmatic Engineer',
    bio: "Gergely Orosz is the author of The Pragmatic Engineer, the #1 technology newsletter on Substack with 300,000+ paid subscribers. He previously worked as an engineering manager at Uber and Booking.com. His writing on software engineering culture is essential reading.",
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=GergelyOrosz',
    linkedinUrl: 'https://linkedin.com/in/gergelyorosz',
    twitterHandle: 'GergelyOrosz',
    websiteUrl: 'https://pragmaticengineer.com',
    topics: ['software engineering', 'engineering management', 'tech careers', 'newsletter business'],
    fitScore: 91,
    stage: 'follow_up',
    priority: 'high',
    notes:
      'Published Ep 38. Huge crossover with his audience. Newsletter follow-up article drove 8k new listeners.',
    episodeTitle: "300k Paid Subscribers: The Pragmatic Engineer's Business Model",
    episodeNumber: 38,
    recordingDate: '2025-09-20T15:00:00Z',
    publishedDate: '2025-10-01T09:00:00Z',
    podcastUrl: 'https://podcast.example.com/episodes/38',
    nextFollowUpDate: '2026-04-15T09:00:00Z',
    outreachCount: 2,
    lastContactedAt: '2025-10-15T10:00:00Z',
    createdAt: '2025-08-01T10:00:00Z',
    updatedAt: '2025-10-15T10:00:00Z',
  },
  {
    id: 'guest_033',
    workspaceId: WORKSPACE_ID,
    name: 'Lenny Rachitsky',
    email: 'lenny@lennysnewsletter.com',
    title: 'Founder & Host',
    company: "Lenny's Newsletter & Podcast",
    bio: "Lenny Rachitsky is the founder of Lenny's Newsletter and Podcast, the most listened-to product management resource in the world. Former PM at Airbnb. 700,000 newsletter subscribers and 5M podcast downloads per month.",
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=LennyRachitsky',
    linkedinUrl: 'https://linkedin.com/in/lennyrachitsky',
    twitterHandle: 'lennysan',
    websiteUrl: 'https://lennysnewsletter.com',
    topics: ['product management', 'creator economy', 'media business', 'podcasting'],
    fitScore: 95,
    stage: 'follow_up',
    priority: 'high',
    notes:
      'Published Ep 39. Perfect episode swap — he had us on his podcast too. Warm relationship.',
    episodeTitle: "Lenny Rachitsky on Building the World's Biggest PM Podcast",
    episodeNumber: 39,
    recordingDate: '2025-10-10T15:00:00Z',
    publishedDate: '2025-10-20T09:00:00Z',
    podcastUrl: 'https://podcast.example.com/episodes/39',
    nextFollowUpDate: '2026-04-20T09:00:00Z',
    outreachCount: 1,
    lastContactedAt: '2025-10-20T10:00:00Z',
    createdAt: '2025-09-01T10:00:00Z',
    updatedAt: '2025-10-20T10:00:00Z',
  },
  {
    id: 'guest_034',
    workspaceId: WORKSPACE_ID,
    name: 'Diana Chen',
    email: 'diana@linear.app',
    title: 'Co-Founder & CPO',
    company: 'Linear',
    bio: "Diana Chen is a co-founder and CPO of Linear, the issue tracker built for high-performance teams. Linear's obsession with speed and design has made it the gold standard in the project management category. She previously led design at Stripe.",
    avatarUrl: 'https://api.dicebear.com/7.x/personas/svg?seed=DianaChen',
    linkedinUrl: 'https://linkedin.com/in/dianalinear',
    twitterHandle: 'diana_linear',
    websiteUrl: 'https://linear.app',
    topics: ['product design', 'developer tools', 'product-led growth', 'startup culture'],
    fitScore: 90,
    stage: 'follow_up',
    priority: 'high',
    notes:
      'Published Ep 36. Design community obsessed. Follow-up idea: Linear\'s approach to AI features.',
    episodeTitle: "Linear's Obsession with Speed: Building the Perfect Project Manager",
    episodeNumber: 36,
    recordingDate: '2025-08-25T15:00:00Z',
    publishedDate: '2025-09-10T09:00:00Z',
    podcastUrl: 'https://podcast.example.com/episodes/36',
    nextFollowUpDate: '2026-03-20T09:00:00Z',
    outreachCount: 2,
    lastContactedAt: '2025-09-10T10:00:00Z',
    createdAt: '2025-07-15T10:00:00Z',
    updatedAt: '2025-09-10T10:00:00Z',
  },
];
